version: "3.8"
services:
  jenkins:
    container_name: jenkins
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - ./jenkins/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    privileged: true  # Docker 실행을 위해 필요한 권한